# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: "https://zhang0peter.com" # the base hostname & protocol for your site
date_format: "ordinal"
title: "zhang0peter的个人博客"
subtitle: "记录生活"
description: "zhang0peter的个人博客"
keywords: 博客, zhang0peter
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3  #主页展示的github仓库数量

# ---------------- #
#      Author      #
# ---------------- #
author: zhang0peter
organization:
organization_url: ""
github_username: zhang0peter
location: HangZhou, China
email: zhang0peter@foxmail.com 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档 

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /atom.xml
feed:
  path: feed.xml
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-feed
    - jemoji
    - jekyll-seo-tag
#     - jekyll-mentions
#     - jekyll-html-pipeline
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhang0peter/zhang0peter.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhang0peter
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhang0peter
    repo: blog-comments
    oauth:
        client_id: 6da837e021706440cec5
        client_secret: 5c980b1358826a24b285211604dbe5d053feb892
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhang0peter
    repo: blog-comments
    clientID: 6da837e021706440cec5
    clientSecret: 5c980b1358826a24b285211604dbe5d053feb892
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-114841473-2
excerpt_separator: ""
# ---------------- #
#    sitemap       #
# ---------------- #

plugins:
  - jekyll-sitemap
# ---------------- #
#    压缩CSS与HTML #
# ---------------- #
sass:
  style: compressed #压缩css

compress_html:     #压缩网页
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]